// playwright.config.js
// Base Playwright configuration for Salesforce demo pre-flight tests
// Auto-generated by sf-demo-playwright

const { execSync } = require('child_process');

// Get org info from sf CLI at config time
function getOrgInfo(alias) {
  try {
    const raw = execSync(`sf org display --target-org ${alias} --json`, { stdio: ['pipe', 'pipe', 'ignore'] }).toString();
    return JSON.parse(raw).result;
  } catch {
    return { instanceUrl: 'https://login.salesforce.com', accessToken: '' };
  }
}

const ORG_ALIAS = process.env.SF_ORG_ALIAS || 'my-demo-org';
const orgInfo = getOrgInfo(ORG_ALIAS);

/** @type {import('@playwright/test').PlaywrightTestConfig} */
module.exports = {
  testDir: '.',
  testMatch: 'demo-preflight.spec.js',
  timeout: 60 * 1000,          // 60s per test (Salesforce LWC can be slow)
  retries: 1,                   // Retry once on flakiness
  workers: 1,                   // Sequential -- demos are stateful
  fullyParallel: false,

  reporter: [
    ['html', { outputFolder: 'demo-report', open: 'never' }],
    ['list']
  ],

  use: {
    baseURL: orgInfo.instanceUrl,
    screenshot: 'on',            // Always capture screenshots
    video: 'retain-on-failure',  // Video only on failure
    trace: 'retain-on-failure',  // Trace only on failure
    headless: true,              // Set to false to watch tests run

    // Inject Salesforce session cookie so we skip the login page
    storageState: {
      cookies: orgInfo.accessToken ? [{
        name: 'sid',
        value: orgInfo.accessToken,
        domain: new URL(orgInfo.instanceUrl).hostname,
        path: '/',
        httpOnly: true,
        secure: true,
        sameSite: 'None'
      }] : [],
      origins: []
    },

    // Standard viewport for Salesforce Lightning
    viewport: { width: 1440, height: 900 },
    actionTimeout: 15000,
    navigationTimeout: 30000
  },

  // Pass org info to tests via env
  globalSetup: undefined,
  projects: [
    {
      name: 'chromium',
      use: {
        browserName: 'chromium',
        // Uncomment to run in a visible browser window:
        // headless: false,
        // slowMo: 500,
      }
    }
  ]
};
