#!/bin/bash
# Demo Pre-flight Check Script
# Auto-generated by sf-demo-playwright
#
# Usage: ./scripts/preflight.sh [org-alias]
# Example: ./scripts/preflight.sh my-demo-org

ORG=${1:-my-demo-org}
REPORT_DIR="demo-report"
SCREENSHOTS_DIR="screenshots"
GUIDE="PRESENTER-GUIDE.md"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║      Demo Pre-flight Check               ║"
echo "╚══════════════════════════════════════════╝"
echo "  Org: $ORG"
echo "  Date: $(date '+%Y-%m-%d %H:%M')"
echo ""

# ── Step 1: Verify Playwright is installed ────────────────────────────────────
if ! npx playwright --version > /dev/null 2>&1; then
  echo "❌ Playwright not found."
  echo "   Run: npm install playwright && npx playwright install chromium"
  exit 1
fi
echo "✅ Playwright installed: $(npx playwright --version)"

# ── Step 2: Verify sf CLI org auth ───────────────────────────────────────────
sf org display --target-org "$ORG" --json > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "❌ Org '$ORG' not authenticated."
  echo "   Run: sf org login web --alias $ORG"
  exit 1
fi
echo "✅ Org authenticated: $ORG"

# ── Step 3: Create output directories ────────────────────────────────────────
mkdir -p "$SCREENSHOTS_DIR"
mkdir -p "$REPORT_DIR"

# ── Step 4: Run the Playwright test suite ────────────────────────────────────
echo ""
echo "Running pre-flight tests..."
echo "────────────────────────────"
npx playwright test demo-preflight.spec.js --reporter=list

PLAYWRIGHT_EXIT=$?

# ── Step 5: Report results ───────────────────────────────────────────────────
echo ""
echo "────────────────────────────"

if [ $PLAYWRIGHT_EXIT -eq 0 ]; then
  echo "✅ All pre-flight checks PASSED"
  echo ""
  echo "You're ready to demo."
  echo ""
  echo "   📋 Presenter guide:  $GUIDE"
  echo "   📸 Screenshots:      $SCREENSHOTS_DIR/"
  echo "   📊 Full report:      $REPORT_DIR/index.html"
  echo ""
else
  echo "❌ Pre-flight FAILED ($PLAYWRIGHT_EXIT test(s) did not pass)"
  echo ""
  echo "   📊 Open report for details: $REPORT_DIR/index.html"
  echo "   🔧 Auto-repair: Run sf-demo-validate in Cursor to fix issues"
  echo ""
  exit 1
fi
